name: iWallet
description: iWallet test case application.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_clean_architecture: ^5.0.4
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
   
